# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_album_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='call_to_action',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='album',
            name='album_title',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='album',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
